### PR TITLE
Implement the placing of ships

### PR DESCRIPTION
**Pull request by TravisWhitehead**
This PR just adds all the code pertaining to placing ships. It ensures that ships cannot be placed partially off-grid, however it doesn't ensure that ships cannot overlap. (That will come in a future PR.)

### CODE REVIEW

**Comment by ghost** [comment]
Let me know when you're done resolving these conflicts. I'll take a look and (hopefully) merge your code.

**Comment by TravisWhitehead** [comment]
Don't merge yet, need to tweak a few things.

**Comment by TravisWhitehead** [comment]
When testing post-merge I ran into a few oddities, so 735d74d fixes 'em. What it changes:

- Make all ship names lowercase to make retrieving them easier, as I realized the view still works if the JSON ship names are lowercase.
- Fix an off-by-one error in for loops iterating over compShips and playerShips.
- Fix an bug where updateShots would report a collision if a shot shared only a row or column with a ship (instead of both)
- Reverse playerHits/Misses and computerHits/Misses, as apparently the view assumes that these describe shots targeting the player/comp, not shots fired by them. (Players' shots were firing at their own board, this fixes that.)
- Create a BatleshipModel method that updates a ship (both the individual member and the ship in the array). I realized that my code for placing ships was updating one but not the other, which meant that the ships used for collision-detection had the wrong positions, so that's my bad.
- Fix an off-by-one where I was placing ships as if they were one longer than they are.
- Update the newModel() test to include playerShips and compShips arrays, so the test will pass.
- And some minor renaming.

**Comment by TravisWhitehead** [comment]
Just kidding, now it's good, for real this time. Maybe.

**Comment by CMCarlsen** [comment]
Travis and I talked through the changes here, and everything seems to checkout. The renaming is a simple change, but helps with clarity. Even squashed another bug in the process. Woo.

Accepting the PR.

**Pull request merged**
