### PR TITLE
Refactors updateShots logic so it's also useful for placing ships (with new methods)

### PR DESCRIPTION
**Pull request by TravisWhitehead**
Wanted to be able to use Sean's code for checking if ships overlap down the road, so I pulled some of the logic into separate methods.

- Ship class now has checkCollision(Coords coordinates).
- BattleshipModel now has class checkShipCollisions(String target, Coords coordinates) which will call each Ship's checkCollision(Coords coordinates) and let us know if a collision is found with any of them (belonging to either the player or computer).
- updateShots(String targetSide, Coords targetArea) just checks for collisions with ships using checkShipCollisions(String target, Coords coordinates) and then adds a shot as a hit or miss, depending on the result.

So everything works how it did before, but now we can check for collisions with ships w/o the firing functionality.

### CODE REVIEW

**Comment by CMCarlsen** [comment]
This PR looks pretty good to me overall, but I have one suggestion. The Ship.checkCollision() method looks fine, but it seems logical for the BattleshipModel.checkShipCollision() to return which ship is actually collided with. It's not hugely important at the moment, but it's a decent piece of information that we might want access to at some point.

If you like this idea, make sure to change the BattleshipModel.updateShot() method to match the return, instead of looking for a Boolean.

I would accept this PR, but as it was @KobaKiju 's code that was changed, I'll defer to him on it, though I think accepting these would be good!

**Comment by TravisWhitehead** [comment]
That's a good idea, and will actually help when I'm checking for ship overlap when placing ships (as I don't want to check collisions against the ship I'm placing, so I can check if it's not the same as the return value). I'll throw up another commit soon.

**Comment by TravisWhitehead** [comment]
Noticed a bug in which shots register as hits somewhat inconsistently. Don't merge, I'll revisit this in the morning.

**Comment by TravisWhitehead** [comment]
Fixed & ready for review. (I just forgot to update the ship placing code to actually set isVert when it changes, as previously it was only the constructor, so everything was defaulting to horizontal.)

**Comment by FiscalClifford** [comment]
The CheckCollision() will be useful for sure, Gonna make some test cases with that

**Comment by ghost** [comment]
Okay, moving that method looks like a good idea. Follows the object-orientated idea a little more. I'm going to go ahead and accept the PR, thanks for waiting.

**Pull request merged**
